import org.apache.geode.cache.Region;
import org.apache.geode.cache.client.ClientCache;
import org.apache.geode.cache.client.ClientCacheFactory;
import org.apache.geode.cache.client.ClientRegionShortcut;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'sbawaskar' at '10/28/17 1:47 PM' with Gradle 2.12
 *
 * @author sbawaskar, @date 10/28/17 1:47 PM
 */
public class Library {
    private ClientCache cache;
    private Region region;

    public Library() {
        this.cache = new ClientCacheFactory().create();
        this.region = this.cache.createClientRegionFactory(ClientRegionShortcut.PROXY).create("test");

        this.cache.getQueryService();
    }
    public void doPut() {
        this.region.put("1", "one");
    }
    public String doGet() {
        return (String) this.region.get("1");
    }
    public static void main(String[] args) {

    }
}
